version: '3.1'

services:

  django_scientist_base:
    image: postgres
    restart: always
    container_name: ${POSTGRES_HOST}
    links:
      - django_web
    env_file:
      - .env

  django_web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django_web
    container_name: django_web
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py shell < init_admin.py
      && python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    working_dir: /ire_site
