# Generated by Django 2.2 on 2022-10-24 07:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('short_title', models.CharField(max_length=32, verbose_name='Сокращенное название')),
                ('short_description', models.TextField(max_length=512, verbose_name='Краткое описание')),
                ('full_description', models.TextField(max_length=8192, verbose_name='Полное описание')),
                ('photo', models.ImageField(upload_to='photos/inventions', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Изобретение',
                'verbose_name_plural': 'Изобретения',
                'ordering': ['full_title'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(max_length=32, verbose_name='Сокращенное название')),
                ('short_description', models.TextField(max_length=512, verbose_name='Краткое описание')),
                ('full_description', models.TextField(max_length=8192, verbose_name='Полное описание')),
                ('logo', models.ImageField(upload_to='photos/organizations', verbose_name='Логотип')),
                ('history', models.TextField(max_length=8192, verbose_name='История')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1830), django.core.validators.MaxValueValidator(2022)], verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Годы',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, unique=True, verbose_name='ФИО')),
                ('short_name', models.CharField(max_length=32, verbose_name='Сокращенное ФИО')),
                ('short_description', models.TextField(max_length=512, verbose_name='Краткое описание')),
                ('full_description', models.TextField(max_length=8192, verbose_name='Полное описание')),
                ('photo', models.ImageField(upload_to='photos/scientists', verbose_name='Фото')),
                ('life_years', models.CharField(max_length=21, validators=[django.core.validators.RegexValidator('[0-9]{2}.[0-9]{2}.[0-9]{4}-[0-9]{2}.[0-9]{2}.[0-9]{4}|[0-9]{2}.[0-9]{2}.[0-9]{4}')], verbose_name='Годы жизни')),
                ('end_year', models.ForeignKey(default=2022, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scientist_end_year', to='scientists_base.Year', verbose_name='Год смерти')),
                ('invention', models.ManyToManyField(blank=True, related_name='scientist_invention', to='scientists_base.Invention', verbose_name='Изобретение')),
                ('organization', models.ManyToManyField(blank=True, related_name='scientist_organization', to='scientists_base.Organization', verbose_name='Организация')),
                ('start_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scientist_start_year', to='scientists_base.Year', verbose_name='Год рождения')),
            ],
            options={
                'verbose_name': 'Ученый',
                'verbose_name_plural': 'Ученые',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='end_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_end_year', to='scientists_base.Year', verbose_name='Год расформирования'),
        ),
        migrations.AddField(
            model_name='organization',
            name='invention',
            field=models.ManyToManyField(blank=True, related_name='organization_invention', to='scientists_base.Invention', verbose_name='Изобретение'),
        ),
        migrations.AddField(
            model_name='organization',
            name='scientist',
            field=models.ManyToManyField(blank=True, related_name='organization_scientist', to='scientists_base.Scientist', verbose_name='Ученый'),
        ),
        migrations.AddField(
            model_name='organization',
            name='start_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_start_year', to='scientists_base.Year', verbose_name='Год создания'),
        ),
        migrations.AddField(
            model_name='invention',
            name='organization',
            field=models.ManyToManyField(blank=True, related_name='invention_organization', to='scientists_base.Organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='invention',
            name='scientist',
            field=models.ManyToManyField(blank=True, related_name='invention_scientist', to='scientists_base.Scientist', verbose_name='Ученый'),
        ),
        migrations.AddField(
            model_name='invention',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scientists_base.Year', verbose_name='Год создания'),
        ),
    ]
