# Generated by Django 2.2 on 2022-10-20 15:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1830), django.core.validators.MaxValueValidator(2022)], verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Годы',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='ФИО')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.CharField(max_length=500, verbose_name='Полное описание')),
                ('photo', models.ImageField(upload_to='photos/scientists', verbose_name='Фото')),
                ('life_years', models.CharField(max_length=50, verbose_name='Годы жизни')),
                ('end_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scientist_end_year', to='scientists_base.Year', verbose_name='Год смерти')),
                ('start_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scientist_start_year', to='scientists_base.Year', verbose_name='Год рождения')),
            ],
            options={
                'verbose_name': 'Ученый',
                'verbose_name_plural': 'Ученые',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Название')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.CharField(max_length=500, verbose_name='Полное описание')),
                ('logo', models.ImageField(blank=True, upload_to='photos/scientists', verbose_name='Логотип')),
                ('history', models.CharField(max_length=500, verbose_name='История')),
                ('end_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_end_year', to='scientists_base.Year', verbose_name='Год расформирования')),
                ('start_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_start_year', to='scientists_base.Year', verbose_name='Год создания')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='Название')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.CharField(max_length=500, verbose_name='Полное описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/scientists', verbose_name='Фото')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scientists_base.Year', verbose_name='Год создания')),
            ],
            options={
                'verbose_name': 'Изобретение',
                'verbose_name_plural': 'Изобретения',
                'ordering': ['title'],
            },
        ),
    ]
