# Generated by Django 2.2 on 2022-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientists_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invention',
            name='photo',
            field=models.ImageField(upload_to='img/inventions', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(upload_to='img/organizations', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='photo',
            field=models.ImageField(upload_to='img/scientists', verbose_name='Фото'),
        ),
    ]
