# Generated by Django 2.2 on 2022-10-20 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientists_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invention',
            name='organization',
            field=models.ManyToManyField(blank=True, null=True, related_name='invention_organization', to='scientists_base.Organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='invention',
            name='scientist',
            field=models.ManyToManyField(blank=True, null=True, related_name='invention_scientist', to='scientists_base.Scientist', verbose_name='Ученый'),
        ),
        migrations.AddField(
            model_name='organization',
            name='invention',
            field=models.ManyToManyField(blank=True, null=True, related_name='organization_invention', to='scientists_base.Invention', verbose_name='Изобретение'),
        ),
        migrations.AddField(
            model_name='organization',
            name='scientist',
            field=models.ManyToManyField(blank=True, null=True, related_name='organization_scientist', to='scientists_base.Scientist', verbose_name='Ученый'),
        ),
        migrations.AddField(
            model_name='scientist',
            name='invention',
            field=models.ManyToManyField(blank=True, null=True, related_name='scientist_invention', to='scientists_base.Invention', verbose_name='Изобретение'),
        ),
        migrations.AddField(
            model_name='scientist',
            name='organization',
            field=models.ManyToManyField(blank=True, null=True, related_name='scientist_organization', to='scientists_base.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='invention',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/inventions', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='invention',
            name='title',
            field=models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='photos/organizations', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='name',
            field=models.CharField(db_index=True, max_length=500, unique=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/scientists', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(db_index=True, unique=True, validators=[django.core.validators.MinValueValidator(1830), django.core.validators.MaxValueValidator(2022)], verbose_name='Год'),
        ),
    ]
